language: python

env:
  matrix:
    - LUA=lua5.3 LUAC=luac5.3

before_install:
  - echo "deb http://deb.debian.org/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get --allow-unauthenticated -t jessie-backports install lua5.3

python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py cythonize
  - pip install .

# command to run tests
script:
  - pytest
