language: python

env:
  matrix:
    - LUA=lua5.2

addons:
  apt:
    packages:
      - lua5.2

python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py cythonize
  - pip install .

# command to run tests
script:
  - pytest
