name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev g++
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools cython build
    - name: Cythonize
      run: |
        python setup.py cythonize
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
